baseURL = "https://danielyoureelewis.github.io/"
languageCode = "en-us"
title = "Daniel Youree Lewis"
relativeURLs = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/posts/:slug/"
